### ISSUE TITLE
modules/Dockerfile.alpine broken

### ISSUE THREAD

**Issue by sebastianhelbig** [nginx/docker-nginx#932]
### Describe the bug

It seems alpine today updated python3. This broke the `modules/Dockerfile.alpine`. `hg clone` fails.

```
…
#10 12.55 (63/63) Installing xz (5.6.2-r0)
#10 12.60 Executing busybox-1.36.1-r29.trigger
#10 12.61 OK: 337 MiB in 129 packages
#10 12.70 + printf '#!/bin/sh\nSETFATTR=true /usr/bin/abuild -F "$@"\n'
#10 12.70 + chmod +x /usr/local/bin/abuild
#10 12.70 + hg clone -r 1.27.1-1 https://hg.nginx.org/pkg-oss/
#10 12.73 Traceback (most recent call last):
#10 12.73   File "/usr/bin/hg", line 57, in <module>
#10 12.73     from mercurial import dispatch
#10 12.73   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
#10 12.73   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
#10 12.73   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
#10 12.73   File "/usr/lib/python3.12/site-packages/hgdemandimport/demandimportpy3.py", line 52, in exec_module
#10 12.73     super().exec_module(module)
#10 12.73   File "<frozen importlib.util>", line 257, in exec_module
#10 12.73   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
#10 12.73   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
#10 12.73   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
#10 12.73   File "/usr/lib/python3.12/site-packages/hgdemandimport/demandimportpy3.py", line 52, in exec_module
#10 12.73     super().exec_module(module)
#10 12.73   File "<frozen importlib.util>", line 267, in exec_module
#10 12.73 AttributeError: partially initialized module 'threading' has no attribute 'RLock' (most likely due to a circular import)
```

**Comment by thresheek** [comment]
I've been notified that this is already fixed in the new Alpine mercurial packages.  Can you please validate? Thanks
